version: "3"
services:
  redis-server:
    image: "redis"
    restart: always
  mongo-db:
    image: "mongo"
    restart: always
    ports:
      - "27018:27017"
  project-app:
    build:
      context: ../
      dockerfile: Bource.JobServer/Dockerfile
    restart: always
    ports:
      - "8186:443"
      - "8187:80"
    depends_on:
      - mongo-db
      - redis-server
