version: "3"
services:
  redis-server:
    image: "redis"
    restart: always
  mongo-db:
    image: "mongo"
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bourceMongoDbAdmin
      - MONGO_INITDB_ROOT_PASSWORD=ZEXdBgew9DoRKUM3rauUbyJRV
    volumes:
      - /mongodb:/data/db
  project-app:
    build:
      context: ../
      dockerfile: Bource.JobServer/Dockerfile
    restart: always
    ports:
      - "8187:80"
    depends_on:
      - mongo-db
      - redis-server
    volumes:
      - ./Contents:/Contents/*